### ISSUE TITLE
Link Broken

### ISSUE THREAD

**Issue by zhaojianghe16** [pharish93/NYTaxiDataMining#1]
Dear friend,
     Could you please upload the data file with OSRM? The link is broken.  Thank you. 

Data used in this project is taken from a kaggle kernal. It can be downloaded from "https://www.kaggle.com/oscarleo/new-york-city-taxi-with-osrm" [ Last accessed on 4/20/2018 , report if link is broken]

Best,
Alan

**Comment by jakirock4** [comment]
Link Broken

**Comment by pharish93** [comment]
The data was part of kaggle competation . seems like they have pulled it down . Sorry about that
